name: Update uv.lock for Dependabot PRs

on:
  pull_request:
    paths:
      - 'pyproject.toml'

permissions:
  contents: write
  pull-requests: write

jobs:
  update-uv-lock:
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.head_ref }}
          
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        
      - name: Update uv.lock
        run: |
          uv lock --upgrade-package bottle --upgrade-package gunicorn
          
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add uv.lock
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "chore: update uv.lock"
            git push
          fi